### ISSUE TITLE
The qrcode module is missing (it's not though)

### ISSUE THREAD

**Issue by psychorror** [wsdfhjxc/ulauncher-qr-code#1]
I first tried "pip install qrcode", it required me to install python-pip. I did that, then went on to install qrcode and did that too. After all that though when using this extension through ulauncher it ultimately says: "Oops the qrcode module is missing... you can install it with: pip install qrcode".

I have checked that I installed qrcode correctly and can create qr codes through terminal. I have tried removing and adding the extension again but to no success.

**Comment by LazyM49** [comment]
Same error here, qr command in terminal works but the extension doesn't

**Comment by wsdfhjxc** [comment]
I can't reproduce the issue, as once the `qrcode` module is installed, and after re-adding the extension, it works fine.

Can you both tell me what distro do you have? This information could be helpful, and I'll try to investigate what's going on.

**Comment by LazyM49** [comment]
I have tested it out again right now, didn't change anything in the configuration or anything and It just worked, maybe an update of some other module or dependency fixed it.

**Comment by psychorror** [comment]
Yeah same here I've just tested it again and it is working. But I also didn't change anything about it so it was probably some obscure issue on our part. Thank you for your time.
